title: Burhan Tuerker's Personal Site
email: burhan.tuerker@gmail.com
description: >-
  Hey there! I'm Burhan.
baseurl: ""
url: ""
markdown: kramdown
sass:
  style: compressed
collections:
  - projects
